### ISSUE TITLE
Resource isn't properly created on darwin target

### ISSUE THREAD

**Issue by ubuntudroid** [goncalossilva/kotlinx-resources#40]
In my `commonTest` module I have a `json` folder with a json5 file in it.

![CleanShot 2023-02-17 at 13 59 15](https://user-images.githubusercontent.com/519867/219659391-75567567-70e4-4178-a50d-508e60aee0ae.png)

I'm using this file in my tests like so:

```kotlin
val resource = Resource("src/commonTest/json/Meals.json5")
assertTrue { resource.exists() }
...
```

This works perfectly fine on the JVM, but not at all on darwin. On the latter, I'm getting a `RuntimeException` when trying to call `readText()` and `exists()` returns `false`.

Any idea what I might be doing wrong?

**Comment by goncalossilva** [comment]
Thanks for the report, @ubuntudroid! That's unexpected. It seems [no path is found](https://github.com/goncalossilva/kotlinx-resources/blob/5705f5cf293ae173fded59aaf7df22f20488b6b0/resources-library/src/darwinMain/kotlin/Resource.kt#L9-L12) for the resource. That would mean the plugin isn't running, or failed to move the resource.

1. Can you confirm you're using the plugin, alongside the library?
2. When you list the tasks for the projects, which ones do you see starting with `copyResources`?
3. Which Gradle version are you using? And Kotlin version?

**Comment by ubuntudroid** [comment]
1. Yes, and it works fine on Android (but maybe the plugin is just needed for iOS?). In my shared `build.gradle.kts`:
```kts
plugins {
    alias(libs.plugins.goncalossilva.test.resources)
}
```
... and my `libs.versions.toml`:
```toml
[versions]
test-resources = "0.2.4"

[libraries]
goncalossilva-test-resources = { module = "com.goncalossilva:resources", version.ref = "test-resources" }

[plugins]
goncalossilva-test-resources = { id = "com.goncalossilva.resources", version.ref = "test-resources" }
```
2. None, which probably isn't a good sign. 😅 
3. Gradle 8.0-rc-2, Kotlin 1.8.0
